export const ACADEMY_FUNDING_SOURCES_2026 = [
  {
    opco_code: "AFDAS",
    year: 2026,
    title: "Financement de la formation pour les structures de moins de 50 salariés",
    source_url: "https://www.afdas.com/entreprise/financer-vos-actions-de-formation/choisir-le-bon-financement/financement-de-la-formation-pour-les-structures-de-moins-de-50-salaries.html",
    source_type: "official_web",
    scope: "PDC <50"
  },
  {
    opco_code: "AKTO",
    year: 2026,
    title: "Règles de prise en charge 2026",
    source_url: "https://www.akto.fr/entreprise/financer-une-formation/regles-de-prise-en-charge/",
    source_type: "official_web",
    scope: "branch-specific"
  },
  {
    opco_code: "ATLAS",
    year: 2026,
    title: "Critères de financement 2026",
    source_url: "https://www.opco-atlas.fr/actualites/decouvrez-les-nouveaux-criteres-de-financement-2026.html",
    source_type: "official_web",
    scope: "branch-specific"
  },
  {
    opco_code: "CONSTRUCTYS",
    year: 2026,
    title: "Conditions de prise en charge 2026",
    source_url: "https://www.constructys.fr/conditions-de-prise-en-charge-2/",
    source_type: "official_web",
    scope: "PDC / branch-specific"
  },
  {
    opco_code: "OPCOMMERCE",
    year: 2026,
    title: "Critères de prise en charge par branche professionnelle",
    source_url: "https://www.lopcommerce.com/entreprise/criteres-de-prise-en-charge-par-branche-professionnelle/",
    source_type: "official_web",
    scope: "branch-specific"
  },
  {
    opco_code: "OCAPIAT",
    year: 2026,
    title: "Règles et dispositifs de prise en charge",
    source_url: "https://www.ocapiat.fr/informations-legales-et-reglementaires/",
    source_type: "official_web",
    scope: "PDC / dispositifs"
  },
  {
    opco_code: "OPCO2I",
    year: 2026,
    title: "2i Solutions financières – plan de développement des compétences",
    source_url: "https://www.opco2i.fr/services-solutions/2i-actions-cles-en-main/",
    source_type: "official_web",
    scope: "PDC <50"
  },
  {
    opco_code: "OPCOEP",
    year: 2026,
    title: "Critères de financement et prise en charge 2026",
    source_url: "https://www.opcoep.fr/criteres-de-financement",
    source_type: "official_web",
    scope: "branch-specific"
  },
  {
    opco_code: "OPCOMOBILITES",
    year: 2026,
    title: "Guides pratiques 2026 – critères de prise en charge",
    source_url: "https://www.opcomobilites.fr/fileadmin/user_upload/documentation/entreprises/guides_pratiques/Guides_pratiques_2026/Metropole_2026/Transports_routiers_de_marchandises_02012026.pdf",
    source_type: "official_web",
    scope: "branch-specific"
  },
  {
    opco_code: "OPCOSANTE",
    year: 2026,
    title: "Plan de développement des compétences – modalités de prise en charge",
    source_url: "https://www.opco-sante.fr/employeur/les-dispositifs-de-formation/plan-de-developpement-des-competences-pdc/",
    source_type: "official_web",
    scope: "branch-specific"
  },
  {
    opco_code: "UNIFORMATION",
    year: 2026,
    title: "Financer votre plan de développement des compétences",
    source_url: "https://www.uniformation.fr/entreprise/formation/dispositifs-de-formation/plan-de-developpement-des-competences/financement",
    source_type: "official_web",
    scope: "PDC / branch-specific"
  }
];

const VERIFIED_AT = "2026-09-28T00:00:00.000Z";

export const ACADEMY_FUNDING_RULES_2026 = [
  {
    opco_code: "AFDAS",
    year: 2026,
    idcc: null,
    branch_label: "Toutes branches Afdas – PDC moins de 50 salariés",
    branch_code: null,
    company_size_min: 1,
    company_size_max: 10,
    scheme: "PDC",
    training_category: "Formation professionnelle",
    annual_ceiling: 1100,
    hourly_ceiling: 40,
    notes: "Plafond annuel de coûts pédagogiques, sous réserve des fonds disponibles. Barème horaire maximum de 40 € par heure et par stagiaire.",
    source_url: "https://www.afdas.com/entreprise/financer-vos-actions-de-formation/choisir-le-bon-financement/financement-de-la-formation-pour-les-structures-de-moins-de-50-salaries.html",
    source_title: "Critères de prise en charge Afdas 2026",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "AFDAS",
    year: 2026,
    idcc: null,
    branch_label: "Toutes branches Afdas – PDC moins de 50 salariés",
    branch_code: null,
    company_size_min: 11,
    company_size_max: 49,
    scheme: "PDC",
    training_category: "Formation professionnelle",
    annual_ceiling: 1800,
    hourly_ceiling: 40,
    notes: "Plafond annuel de coûts pédagogiques, sous réserve des fonds disponibles. Barème horaire maximum de 40 € par heure et par stagiaire.",
    source_url: "https://www.afdas.com/entreprise/financer-vos-actions-de-formation/choisir-le-bon-financement/financement-de-la-formation-pour-les-structures-de-moins-de-50-salaries.html",
    source_title: "Critères de prise en charge Afdas 2026",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "AKTO",
    year: 2026,
    idcc: "1516",
    branch_label: "Organismes de formation",
    branch_code: "OF",
    company_size_min: 1,
    company_size_max: 49,
    scheme: "Plan conventionnel",
    training_category: "Tous thèmes",
    annual_ceiling: 10000,
    hourly_ceiling: 60,
    day_ceiling: 2000,
    notes: "Le budget PDC 2026 de la branche est indiqué comme intégralement engagé. Le plan conventionnel peut financer les dossiers éligibles : plafond annuel 10 000 € par entreprise de moins de 50 salariés ; inter plafonné à 60 €/h/salarié ; intra plafonné à 2 000 €/jour pour 3 stagiaires minimum.",
    source_url: "https://www.akto.fr/regles-de-prise-en-charge-organisme-de-formation/",
    source_title: "Règles de prise en charge 2026 – Organismes de formation",
    valid_from: "2026-01-02",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "ATLAS",
    year: 2026,
    idcc: "2120",
    branch_label: "Banque",
    branch_code: "BANQUE",
    company_size_min: 1,
    company_size_max: 10,
    scheme: "PDC",
    training_category: "Toute formation éligible au PDC",
    annual_ceiling: 3200,
    notes: "Plafond annuel par entreprise, sous réserve de fonds disponibles.",
    source_url: "https://www.opco-atlas.fr/criteres-financement/banque",
    source_title: "Critères de financement 2026 – Banque",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "ATLAS",
    year: 2026,
    idcc: "2120",
    branch_label: "Banque",
    branch_code: "BANQUE",
    company_size_min: 11,
    company_size_max: 49,
    scheme: "PDC",
    training_category: "Toute formation éligible au PDC",
    annual_ceiling: 5600,
    notes: "Plafond annuel par entreprise, sous réserve de fonds disponibles.",
    source_url: "https://www.opco-atlas.fr/criteres-financement/banque",
    source_title: "Critères de financement 2026 – Banque",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "OPCOMMERCE",
    year: 2026,
    idcc: "1517",
    branch_label: "Commerces de détail non alimentaires",
    branch_code: "CDNA",
    company_size_min: 1,
    company_size_max: 10,
    scheme: "Compétences+",
    training_category: "Plan de développement des compétences",
    annual_ceiling: 1350,
    notes: "Budget annuel comprenant uniquement la prise en charge des coûts pédagogiques au réel. Critères en vigueur à compter du 01/05/2026.",
    source_url: "https://www.lopcommerce.com/media/0fddqg4x/cpc_cdna.pdf",
    source_title: "Critères de prise en charge 2026 – Commerces de détail non alimentaires",
    valid_from: "2026-05-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "OPCOMMERCE",
    year: 2026,
    idcc: "1517",
    branch_label: "Commerces de détail non alimentaires",
    branch_code: "CDNA",
    company_size_min: 11,
    company_size_max: 49,
    scheme: "Compétences+",
    training_category: "Plan de développement des compétences",
    annual_ceiling: 1900,
    notes: "Budget annuel comprenant uniquement la prise en charge des coûts pédagogiques au réel. Critères en vigueur à compter du 01/05/2026.",
    source_url: "https://www.lopcommerce.com/media/0fddqg4x/cpc_cdna.pdf",
    source_title: "Critères de prise en charge 2026 – Commerces de détail non alimentaires",
    valid_from: "2026-05-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "OPCOMMERCE",
    year: 2026,
    idcc: "2216",
    branch_label: "Commerce à prédominance alimentaire (détail et gros)",
    branch_code: "PREDOM_ALIM",
    company_size_min: 1,
    company_size_max: 10,
    scheme: "Compétences+",
    training_category: "Plan de développement des compétences",
    annual_ceiling: 2000,
    notes: "Budget annuel comprenant l’action de formation et les salaires dans la limite indiquée par le barème ; frais annexes non pris en charge. Critères en vigueur à compter du 18/03/2026.",
    source_url: "https://www.lopcommerce.com/media/shbkyxa1/cpc_predom.pdf",
    source_title: "Critères de prise en charge 2026 – Commerce à prédominance alimentaire",
    valid_from: "2026-03-18",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "OPCOMMERCE",
    year: 2026,
    idcc: "2216",
    branch_label: "Commerce à prédominance alimentaire (détail et gros)",
    branch_code: "PREDOM_ALIM",
    company_size_min: 11,
    company_size_max: 49,
    scheme: "Compétences+",
    training_category: "Plan de développement des compétences",
    annual_ceiling: 4000,
    notes: "Budget annuel comprenant l’action de formation et les salaires dans la limite indiquée par le barème ; frais annexes non pris en charge. Critères en vigueur à compter du 18/03/2026.",
    source_url: "https://www.lopcommerce.com/media/shbkyxa1/cpc_predom.pdf",
    source_title: "Critères de prise en charge 2026 – Commerce à prédominance alimentaire",
    valid_from: "2026-03-18",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "OPCOEP",
    year: 2026,
    idcc: "1512",
    branch_label: "Promotion immobilière",
    branch_code: "PROMO_IMMO",
    company_size_min: 1,
    company_size_max: 10,
    scheme: "PDC",
    training_category: "Plan de développement des compétences",
    annual_ceiling: 8000,
    notes: "Plafond de financement entreprise. Durée minimale 3 h 30. Les barèmes sont applicables sous réserve de fonds disponibles et peuvent évoluer en cours d’année.",
    source_url: "https://www.opcoep.fr/criteres-de-financement?branche=172",
    source_title: "Critères de financement 2026 – Promotion immobilière",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "OPCOEP",
    year: 2026,
    idcc: "1512",
    branch_label: "Promotion immobilière",
    branch_code: "PROMO_IMMO",
    company_size_min: 11,
    company_size_max: 49,
    scheme: "PDC",
    training_category: "Plan de développement des compétences",
    annual_ceiling: 12000,
    notes: "Plafond de financement entreprise. Durée minimale 3 h 30. Les barèmes sont applicables sous réserve de fonds disponibles et peuvent évoluer en cours d’année.",
    source_url: "https://www.opcoep.fr/criteres-de-financement?branche=172",
    source_title: "Critères de financement 2026 – Promotion immobilière",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "OCAPIAT",
    year: 2026,
    idcc: null,
    branch_label: "Tous secteurs OCAPIAT – catalogue Offre régionale",
    branch_code: null,
    company_size_min: 1,
    company_size_max: 49,
    scheme: "Catalogue Offre régionale",
    training_category: "Formations du catalogue OCAPIAT",
    coverage_percent: 100,
    notes: "Pour les entreprises de moins de 50 salariés, les coûts pédagogiques des formations du catalogue OCAPIAT sont financés à 100 % sur fonds mutualisés, dans la limite des fonds disponibles.",
    source_url: "https://www.ocapiat.fr/catalogue-de-formations-et-financement/",
    source_title: "Catalogue de formations et financement OCAPIAT",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "CONSTRUCTYS",
    year: 2026,
    idcc: null,
    branch_label: "Bâtiment",
    branch_code: "BATIMENT",
    company_size_min: 11,
    company_size_max: 299,
    scheme: "PDC",
    training_category: "Actions de formation Bâtiment",
    hourly_ceiling: 19,
    notes: "Pour les demandes reçues à compter du 1er juin 2026, Constructys indique un plafond horaire de 19 € pour le PDC du Bâtiment des entreprises de 11 à moins de 300 salariés. Cette règle n’est pas appliquée automatiquement à un SIRET tant que l’IDCC précis n’est pas mappé.",
    source_url: "https://www.constructys.fr/conditions-de-prise-en-charge-2/",
    source_title: "Conditions de prise en charge Constructys 2026",
    valid_from: "2026-06-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "ATLAS",
    year: 2026,
    idcc: "0787",
    branch_label: "Expertise comptable, commissariat aux comptes et audit",
    branch_code: "EXPERTISE_COMPTABLE",
    company_size_min: null,
    company_size_max: null,
    scheme: "Critères de financement 2026",
    training_category: "Selon dispositif et taille d'entreprise",
    notes: "Critères 2026 définis par la branche Expertise comptable, commissariat aux comptes et audit. Les montants varient selon le dispositif, l'effectif et les priorités de branche. Utiliser la source officielle Atlas pour le barème applicable au dossier.",
    source_url: "https://www.opco-atlas.fr/criteres-financement?branche=219",
    source_title: "Critères de financement 2026 – Expertise comptable, commissariat aux comptes et audit",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "AKTO",
    year: 2026,
    idcc: null,
    branch_label: "AKTO – barèmes 2026 par branche",
    branch_code: null,
    scheme: "PDC / critères de branche",
    training_category: "Selon branche professionnelle",
    notes: "AKTO publie des règles de prise en charge 2026 différentes selon la branche. Pour une entreprise sans convention collective ou relevant de l'interprofession, les critères 2026 prévoient notamment un budget PDC de 2 500 € (<11 salariés) ou 4 000 € (11–49) dans l'hexagone, avec plafonds spécifiques. Pour les autres branches, appliquer la page de critères dédiée à l'IDCC.",
    source_url: "https://www.akto.fr/entreprise/financer-une-formation/regles-de-prise-en-charge/",
    source_title: "Règles de prise en charge AKTO 2026",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "partial"
  },
  {
    opco_code: "ATLAS",
    year: 2026,
    idcc: null,
    branch_label: "Atlas – critères 2026 par branche",
    branch_code: null,
    scheme: "PDC / critères de branche",
    training_category: "Selon branche professionnelle",
    notes: "Atlas publie des critères 2026 spécifiques à chaque branche. Lorsque l'IDCC est connu, le barème correspondant doit être utilisé. Cette règle générique sert de filet de sécurité lorsqu'aucun barème chiffré n'a encore été normalisé dans AUTONOMIA.",
    source_url: "https://www.opco-atlas.fr/criteres-financement",
    source_title: "Critères de financement Atlas 2026",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "partial"
  },
  {
    opco_code: "CONSTRUCTYS",
    year: 2026,
    idcc: null,
    branch_label: "Constructys – conditions de prise en charge 2026",
    branch_code: null,
    scheme: "PDC / critères sectoriels",
    training_category: "Bâtiment / Travaux publics / Négoce matériaux",
    notes: "Constructys applique des conditions de prise en charge 2026 selon le secteur, l'effectif et le dispositif. Utiliser la source officielle pour le barème correspondant à l'entreprise.",
    source_url: "https://www.constructys.fr/conditions-de-prise-en-charge-2/",
    source_title: "Conditions de prise en charge Constructys 2026",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "partial"
  },
  {
    opco_code: "OPCOMMERCE",
    year: 2026,
    idcc: null,
    branch_label: "L'Opcommerce – critères 2026 par branche",
    branch_code: null,
    scheme: "PDC / Compétences+",
    training_category: "Selon branche professionnelle",
    notes: "Les critères 2026 sont définis par chacune des branches de l'Opcommerce. Lorsque l'IDCC est connu, appliquer le barème de branche correspondant.",
    source_url: "https://www.lopcommerce.com/entreprise/criteres-de-prise-en-charge-par-branche-professionnelle/",
    source_title: "Critères de prise en charge L'Opcommerce 2026",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "partial"
  },
  {
    opco_code: "OCAPIAT",
    year: 2026,
    idcc: null,
    branch_label: "OCAPIAT – dispositifs et critères 2026",
    branch_code: null,
    scheme: "PDC / dispositifs OCAPIAT",
    training_category: "Selon secteur et dispositif",
    notes: "OCAPIAT applique des règles selon le secteur, la taille de l'entreprise et le dispositif mobilisé. Les formations du catalogue Offre régionale peuvent être financées à 100 % pour les entreprises de moins de 50 salariés, sous réserve des fonds disponibles.",
    source_url: "https://www.ocapiat.fr/catalogue-de-formations-et-financement/",
    source_title: "Catalogue de formations et financement OCAPIAT 2026",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "OPCO2I",
    year: 2026,
    idcc: null,
    branch_label: "OPCO 2i – critères et solutions financières 2026",
    branch_code: null,
    scheme: "PDC / solutions financières",
    training_category: "Selon branche industrielle",
    notes: "Les prises en charge OPCO 2i dépendent de la branche, de l'effectif et du dispositif. Utiliser les critères et solutions financières 2026 correspondant à la branche de l'entreprise.",
    source_url: "https://www.opco2i.fr/services-solutions/2i-actions-cles-en-main/",
    source_title: "OPCO 2i – solutions financières 2026",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "partial"
  },
  {
    opco_code: "OPCOEP",
    year: 2026,
    idcc: null,
    branch_label: "Opco EP – critères 2026 par branche",
    branch_code: null,
    scheme: "PDC / critères de branche",
    training_category: "Selon branche professionnelle",
    notes: "Opco EP publie des plafonds et priorités 2026 par branche. Les critères peuvent évoluer en cours d'année. Lorsque l'IDCC est connu, appliquer le barème de la branche correspondante.",
    source_url: "https://www.opcoep.fr/criteres-de-financement",
    source_title: "Critères de financement Opco EP 2026",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "partial"
  },
  {
    opco_code: "OPCOMOBILITES",
    year: 2026,
    idcc: null,
    branch_label: "OPCO Mobilités – guides pratiques 2026",
    branch_code: null,
    scheme: "PDC / critères de branche",
    training_category: "Selon branche Mobilités",
    notes: "OPCO Mobilités publie des guides pratiques 2026 par branche. Les modalités varient selon la branche, l'effectif et le dispositif. Utiliser le guide correspondant à l'IDCC.",
    source_url: "https://www.opcomobilites.fr/",
    source_title: "Guides pratiques OPCO Mobilités 2026",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "partial"
  },
  {
    opco_code: "OPCOSANTE",
    year: 2026,
    idcc: null,
    branch_label: "OPCO Santé – PDC 2026",
    branch_code: null,
    scheme: "PDC",
    training_category: "Selon secteur et fonds mobilisés",
    notes: "Pour les entreprises de moins de 50 salariés relevant du dispositif concerné, OPCO Santé publie en 2026 des prises en charge pouvant couvrir 100 % des coûts pédagogiques, avec plafonds et conditions selon la branche et le fonds mobilisé. Vérifier la synthèse applicable à la structure.",
    source_url: "https://www.opco-sante.fr/employeur/notre-offres-de-services/on-enrichit-nos-pratiques-rh/le-plan-de-developpement-des-competences/",
    source_title: "Plan de développement des compétences OPCO Santé 2026",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "partial"
  },
  {
    opco_code: "UNIFORMATION",
    year: 2026,
    idcc: null,
    branch_label: "Uniformation – financements PDC 2026",
    branch_code: null,
    scheme: "PDC",
    training_category: "Selon secteur, profil et financement mobilisé",
    notes: "Uniformation propose plusieurs solutions de financement 2026 selon le secteur d'activité, la taille de la structure et les contributions disponibles. Le barème doit être déterminé avec les filtres de profil et de secteur.",
    source_url: "https://www.uniformation.fr/particulier/salaries/formation-et-financements/autres-dispositifs-de-formation/le-plan-de-developpement-des-competences/financement",
    source_title: "Financer votre plan de développement des compétences – Uniformation 2026",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "partial"
  }
];
