export const ACADEMY_FUNDING_SOURCES_2026 = [
  {
    opco_code: "AFDAS",
    year: 2026,
    title: "Financement de la formation pour les structures de moins de 50 salariés",
    source_url: "https://www.afdas.com/entreprise/financer-vos-actions-de-formation/choisir-le-bon-financement/financement-de-la-formation-pour-les-structures-de-moins-de-50-salaries.html",
    source_type: "official_web",
    scope: "PDC <50"
  },
  {
    opco_code: "AKTO",
    year: 2026,
    title: "Règles de prise en charge 2026",
    source_url: "https://www.akto.fr/entreprise/financer-une-formation/regles-de-prise-en-charge/",
    source_type: "official_web",
    scope: "branch-specific"
  },
  {
    opco_code: "ATLAS",
    year: 2026,
    title: "Critères de financement 2026",
    source_url: "https://www.opco-atlas.fr/actualites/decouvrez-les-nouveaux-criteres-de-financement-2026.html",
    source_type: "official_web",
    scope: "branch-specific"
  },
  {
    opco_code: "CONSTRUCTYS",
    year: 2026,
    title: "Conditions de prise en charge 2026",
    source_url: "https://www.constructys.fr/conditions-de-prise-en-charge-2/",
    source_type: "official_web",
    scope: "PDC / branch-specific"
  },
  {
    opco_code: "OPCOMMERCE",
    year: 2026,
    title: "Critères de prise en charge par branche professionnelle",
    source_url: "https://www.lopcommerce.com/entreprise/criteres-de-prise-en-charge-par-branche-professionnelle/",
    source_type: "official_web",
    scope: "branch-specific"
  },
  {
    opco_code: "OCAPIAT",
    year: 2026,
    title: "Règles et dispositifs de prise en charge",
    source_url: "https://www.ocapiat.fr/informations-legales-et-reglementaires/",
    source_type: "official_web",
    scope: "PDC / dispositifs"
  },
  {
    opco_code: "OPCO2I",
    year: 2026,
    title: "2i Solutions financières – plan de développement des compétences",
    source_url: "https://www.opco2i.fr/services-solutions/2i-actions-cles-en-main/",
    source_type: "official_web",
    scope: "PDC <50"
  },
  {
    opco_code: "OPCOEP",
    year: 2026,
    title: "Critères de financement et prise en charge 2026",
    source_url: "https://www.opcoep.fr/criteres-de-financement",
    source_type: "official_web",
    scope: "branch-specific"
  },
  {
    opco_code: "OPCOMOBILITES",
    year: 2026,
    title: "Guides pratiques 2026 – critères de prise en charge",
    source_url: "https://www.opcomobilites.fr/entreprise/financer-les-projets-de-formation-de-mes-salaries",
    source_type: "official_web",
    scope: "branch-specific"
  },
  {
    opco_code: "OPCOSANTE",
    year: 2026,
    title: "Plan de développement des compétences – modalités de prise en charge",
    source_url: "https://www.opco-sante.fr/employeur/les-dispositifs-de-formation/plan-de-developpement-des-competences-pdc/",
    source_type: "official_web",
    scope: "branch-specific"
  },
  {
    opco_code: "UNIFORMATION",
    year: 2026,
    title: "Financer votre plan de développement des compétences",
    source_url: "https://www.uniformation.fr/entreprise/formation/dispositifs-de-formation/plan-de-developpement-des-competences/financement",
    source_type: "official_web",
    scope: "PDC / branch-specific"
  }
];

const VERIFIED_AT = "2026-09-28T00:00:00.000Z";

export const ACADEMY_FUNDING_RULES_2026 = [
  {
    opco_code: "AFDAS",
    year: 2026,
    idcc: null,
    branch_label: "Toutes branches Afdas – PDC moins de 50 salariés",
    branch_code: null,
    company_size_min: 1,
    company_size_max: 10,
    scheme: "PDC",
    training_category: "Formation professionnelle",
    annual_ceiling: 1100,
    hourly_ceiling: 40,
    notes: "Plafond annuel de coûts pédagogiques, sous réserve des fonds disponibles. Barème horaire maximum de 40 € par heure et par stagiaire.",
    source_url: "https://www.afdas.com/entreprise/financer-vos-actions-de-formation/choisir-le-bon-financement/financement-de-la-formation-pour-les-structures-de-moins-de-50-salaries.html",
    source_title: "Critères de prise en charge Afdas 2026",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "AFDAS",
    year: 2026,
    idcc: null,
    branch_label: "Toutes branches Afdas – PDC moins de 50 salariés",
    branch_code: null,
    company_size_min: 11,
    company_size_max: 49,
    scheme: "PDC",
    training_category: "Formation professionnelle",
    annual_ceiling: 1800,
    hourly_ceiling: 40,
    notes: "Plafond annuel de coûts pédagogiques, sous réserve des fonds disponibles. Barème horaire maximum de 40 € par heure et par stagiaire.",
    source_url: "https://www.afdas.com/entreprise/financer-vos-actions-de-formation/choisir-le-bon-financement/financement-de-la-formation-pour-les-structures-de-moins-de-50-salaries.html",
    source_title: "Critères de prise en charge Afdas 2026",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "AKTO",
    year: 2026,
    idcc: "1516",
    branch_label: "Organismes de formation",
    branch_code: "OF",
    company_size_min: 1,
    company_size_max: 49,
    scheme: "Plan conventionnel",
    training_category: "Tous thèmes",
    annual_ceiling: 10000,
    hourly_ceiling: 60,
    day_ceiling: 2000,
    notes: "Le budget PDC 2026 de la branche est indiqué comme intégralement engagé. Le plan conventionnel peut financer les dossiers éligibles : plafond annuel 10 000 € par entreprise de moins de 50 salariés ; inter plafonné à 60 €/h/salarié ; intra plafonné à 2 000 €/jour pour 3 stagiaires minimum.",
    source_url: "https://www.akto.fr/regles-de-prise-en-charge-organisme-de-formation/",
    source_title: "Règles de prise en charge 2026 – Organismes de formation",
    valid_from: "2026-01-02",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "ATLAS",
    year: 2026,
    idcc: "2120",
    branch_label: "Banque",
    branch_code: "BANQUE",
    company_size_min: 1,
    company_size_max: 10,
    scheme: "PDC",
    training_category: "Toute formation éligible au PDC",
    annual_ceiling: 3200,
    notes: "Plafond annuel par entreprise, sous réserve de fonds disponibles.",
    source_url: "https://www.opco-atlas.fr/criteres-financement/banque",
    source_title: "Critères de financement 2026 – Banque",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "ATLAS",
    year: 2026,
    idcc: "2120",
    branch_label: "Banque",
    branch_code: "BANQUE",
    company_size_min: 11,
    company_size_max: 49,
    scheme: "PDC",
    training_category: "Toute formation éligible au PDC",
    annual_ceiling: 5600,
    notes: "Plafond annuel par entreprise, sous réserve de fonds disponibles.",
    source_url: "https://www.opco-atlas.fr/criteres-financement/banque",
    source_title: "Critères de financement 2026 – Banque",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "OPCOMMERCE",
    year: 2026,
    idcc: "1517",
    branch_label: "Commerces de détail non alimentaires",
    branch_code: "CDNA",
    company_size_min: 1,
    company_size_max: 10,
    scheme: "Compétences+",
    training_category: "Plan de développement des compétences",
    annual_ceiling: 1350,
    notes: "Budget annuel comprenant uniquement la prise en charge des coûts pédagogiques au réel. Critères en vigueur à compter du 01/05/2026.",
    source_url: "https://www.lopcommerce.com/media/0fddqg4x/cpc_cdna.pdf",
    source_title: "Critères de prise en charge 2026 – Commerces de détail non alimentaires",
    valid_from: "2026-05-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "OPCOMMERCE",
    year: 2026,
    idcc: "1517",
    branch_label: "Commerces de détail non alimentaires",
    branch_code: "CDNA",
    company_size_min: 11,
    company_size_max: 49,
    scheme: "Compétences+",
    training_category: "Plan de développement des compétences",
    annual_ceiling: 1900,
    notes: "Budget annuel comprenant uniquement la prise en charge des coûts pédagogiques au réel. Critères en vigueur à compter du 01/05/2026.",
    source_url: "https://www.lopcommerce.com/media/0fddqg4x/cpc_cdna.pdf",
    source_title: "Critères de prise en charge 2026 – Commerces de détail non alimentaires",
    valid_from: "2026-05-01",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "OPCOMMERCE",
    year: 2026,
    idcc: "2216",
    branch_label: "Commerce à prédominance alimentaire (détail et gros)",
    branch_code: "PREDOM_ALIM",
    company_size_min: 1,
    company_size_max: 10,
    scheme: "Compétences+",
    training_category: "Plan de développement des compétences",
    annual_ceiling: 2000,
    notes: "Budget annuel comprenant l’action de formation et les salaires dans la limite indiquée par le barème ; frais annexes non pris en charge. Critères en vigueur à compter du 18/03/2026.",
    source_url: "https://www.lopcommerce.com/media/shbkyxa1/cpc_predom.pdf",
    source_title: "Critères de prise en charge 2026 – Commerce à prédominance alimentaire",
    valid_from: "2026-03-18",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  },
  {
    opco_code: "OPCOMMERCE",
    year: 2026,
    idcc: "2216",
    branch_label: "Commerce à prédominance alimentaire (détail et gros)",
    branch_code: "PREDOM_ALIM",
    company_size_min: 11,
    company_size_max: 49,
    scheme: "Compétences+",
    training_category: "Plan de développement des compétences",
    annual_ceiling: 4000,
    notes: "Budget annuel comprenant l’action de formation et les salaires dans la limite indiquée par le barème ; frais annexes non pris en charge. Critères en vigueur à compter du 18/03/2026.",
    source_url: "https://www.lopcommerce.com/media/shbkyxa1/cpc_predom.pdf",
    source_title: "Critères de prise en charge 2026 – Commerce à prédominance alimentaire",
    valid_from: "2026-03-18",
    valid_to: "2026-12-31",
    verified_at: VERIFIED_AT,
    evidence_status: "verified"
  }
];
