-- Intelligence V2 read models.
-- Classification/fit/staffing rows are generated by the application persistence layer.
-- Existing production data was backfilled separately and is not a portable seed.

create or replace view public.opportunity_intelligence_v2
with (security_invoker=true)
as
select
  o.id,
  o.opportunity_type,
  o.title,
  o.description,
  o.published_at,
  o.deadline_at,
  case
    when o.deadline_at is null then 'unknown'
    when o.deadline_at < now() then 'closed_by_deadline'
    else 'open_by_deadline'
  end as actionability_state,
  case
    when o.deadline_at is null then null
    else floor(extract(epoch from (o.deadline_at-now()))/86400)::int
  end as days_to_deadline,
  o.status,
  o.location,
  o.budget_min,
  o.budget_max,
  org.canonical_name as buyer_name,
  classif.payload->'tags' as ai_tags,
  (classif.payload->>'is_ai_related')::boolean as is_ai_related,
  nullif(fit.payload->>'score','')::numeric as autonomia_fit_score,
  nullif(fit.payload->>'coverage_percent','')::numeric as fit_coverage_percent,
  staffing.payload->'roles' as inferred_staffing_roles,
  o.first_seen_at,
  o.last_seen_at
from public.opportunities o
left join public.organizations org on org.id=o.buyer_org_id
left join lateral (
  select a.payload
  from public.analyses a
  where a.opportunity_id=o.id and a.analysis_type='market_classification_v2'
  order by a.created_at desc
  limit 1
) classif on true
left join lateral (
  select a.payload
  from public.analyses a
  where a.opportunity_id=o.id and a.analysis_type='autonomia_fit_v2'
  order by a.created_at desc
  limit 1
) fit on true
left join lateral (
  select a.payload
  from public.analyses a
  where a.opportunity_id=o.id and a.analysis_type='staffing_requirements_v2'
  order by a.created_at desc
  limit 1
) staffing on true;

create or replace view public.buyer_market_intelligence_v1
with (security_invoker=true)
as
select
  org.id as buyer_org_id,
  org.canonical_name as buyer_name,
  org.siren,
  org.siret,
  count(pa.id)::int as award_rows,
  count(distinct pa.supplier_org_id)::int as observed_suppliers,
  sum(pa.amount) filter (where pa.amount is not null) as known_amount_total,
  avg(pa.amount) filter (where pa.amount is not null) as known_amount_average,
  min(pa.award_date) as first_award_date,
  max(pa.award_date) as last_award_date,
  count(pa.id) filter (
    where lower(coalesce(pa.object,'')) ~
      '(intelligence artificielle|ia generative|machine learning|data science|llm|chatgpt|copilot|ai act|automatisation|agent)'
  )::int as ai_related_award_rows
from public.organizations org
join public.public_awards pa on pa.buyer_org_id=org.id
group by org.id,org.canonical_name,org.siren,org.siret;

comment on view public.opportunity_intelligence_v2 is
  'Preferred V2 decision-support view. Tags, fit and staffing are inferred; source facts remain in opportunities/raw_items.';

comment on view public.buyer_market_intelligence_v1 is
  'Factual aggregation of observed public-award rows by buyer.';
